book/urls.py
from django.urls import path

from . import views

app_name = 'library'

urlpatterns = [
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author'),
    path('author_list/', views.AuthorListView.as_view(), name='author_list'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book'),
    path('book_list/', views.BookListView.as_view(), name='book_list'),
    path('genre/<int:pk>/', views.GenreDetailView.as_view(), name='genre'),
    path('genre_list/', views.GenreListView.as_view(), name='genre_list'),
    path('reward/<int:pk>/', views.RewardDetailView.as_view(), name='reward'),
    path('reward_list/', views.RewardListView.as_view(), name='reward_list'),
    path('', views.main_view, name='main'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
]

book/models.py
from django.db import models


class Genre(models.Model):
    name = models.CharField('Название жанра ', max_length=100)
    description = models.CharField('описание жанра ', max_length=2000, blank=True)

    def __str__(self):
        return self.name


class Reward(models.Model):
    name = models.CharField('Название премии ', max_length=100)
    date = models.DateField('Дата получения ', blank=True, null=True)
    description = models.CharField('Описание премии ', max_length=2000, blank=True)

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField('Имя', max_length=100)
    second_name = models.CharField('Отчество', max_length=100, blank=True)
    surname = models.CharField('Фамилия', max_length=100)
    birthday = models.DateField('Дата рождения ', blank=True, null=True)
    deathday = models.DateField('Дата смерти ', blank=True, null=True)
    description = models.CharField('Биография ', max_length=2000, blank=True)
    rewards = models.ManyToManyField(
        Reward,
        verbose_name='Награды',
        related_name='authors',
        blank=True,
        # on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.first_name


class Book(models.Model):
    title = models.CharField('Название книги ', max_length=100)
    description = models.CharField('Биография ', max_length=2000, blank=True)
    genres = models.ManyToManyField(
        Genre,
        verbose_name='Жанры книги ',
        related_name='books',
        blank=True,
        # on_delete=models.CASCADE,
    )
    author = models.ManyToManyField(
        Author,
        verbose_name=' Автор книги',
        related_name='book',
        # on_delete=models.CASCADE,
    )
    publish_date = models.DateField('Дата публикации ')

    def __str__(self):
        return self.title

book/views.py
from django.views import generic
from django.shortcuts import render

from .models import Author, Book, Genre, Reward


class AuthorListView(generic.ListView):
    model = Author
    template_name = 'author/author_list.html'
    context_object_name = "author_list"


class AuthorDetailView(generic.DetailView):
    model = Author
    template_name = 'author/author.html'
    context_object_name = "author"


class BookListView(generic.ListView):
    model = Book
    template_name = 'book/book_list.html'
    context_object_name = "book_list"


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'book/book.html'
    context_object_name = "book"


class GenreListView(generic.ListView):
    model = Genre
    template_name = 'genre/genre_list.html'
    context_object_name = "genre_list"


class GenreDetailView(generic.DetailView):
    model = Genre
    template_name = 'genre/genre.html'
    context_object_name = "genre"


class RewardListView(generic.ListView):
    model = Reward
    template_name = 'reward/reward_list.html'
    context_object_name = "reward_list"


class RewardDetailView(generic.DetailView):
    model = Reward
    template_name = 'reward/reward.html'
    context_object_name = "reward"

def main_view(request):
    return render(request, 'main.html')

book/templates/author/author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{author}}</h1>
<h2>{{author.second_name}}</h2>
{% if author.description %}
    <h3>Описнаие автора: </h3>
    <h3>{{author.description}}</h3>
{% else %}
    <h3>Описание отсутствует</h3>
{% endif %}
{% if author.birthday %}
    <h3>: </h3>
    <h3>{{author.birthday}}</h3>
{% else %}
    <h3>день рождения отсутствует</h3>
{% endif %}
{% if author.deathday %}
    <h3>: </h3>
    <h3>{{author.deathday}}</h3>
{% else %}
    <h3>день смерти отсутствует</h3>
{% endif %}
<a href="{%url 'library:book_list'%}">back</a>
</body>
</html>

book/templates/author/author_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Список авторов</h1>
    {% if  author_list %}
        <ul>
            {% for author in author_list %}
                <li><a href="{% url 'library:author' author.id %}">{{ author }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Нет информации</h2>
    {% endif %}
</body>
</html>

book/templates/book/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{book}}</h1>
{% if book.description %}
    <h3>Описнаие кинги: </h3>
    <h3>{{book.description}}</h3>
{% else %}
    <h3>Описание отсутствует</h3>
{% endif %}
{% if book.description %}
    <h3>Описнаие кинги: </h3>
    <h3>{{book.description}}</h3>
{% else %}
    <h3>Описание отсутствует</h3>
{% endif %}
"""{% if book.genre %}
    <h3>жанр кинги: </h3>
    <h3>{{book.genre}}</h3>
{% else %}
    <h3>жанр отсутствует</h3>
{% endif %}
{% if book.author %}
    <h3>автор кинги: </h3>
    <h3>{{book.author}}</h3>
{% else %}
    <h3>автор отсутствует</h3>
{% endif %}"""
<a href="{%url 'library:book_list'%}">back</a>
</body>
</html>

book/templates/book/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Список книг</h1>
    {% if  book_list %}
        <ul>
            {% for book in book_list %}
                <li><a href="{% url 'library:book' book.id %}">{{ book }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Нет информации</h2>
    {% endif %}
</body>
</html>

book/templates/genre/genre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> About {{genre}}</title>
</head>
<body>
<h1>{{genre}}</h1>
{% if genre.description %}
    <h3>Описнаие жанра: </h3>
    <h3>{{genre.description}}</h3>
{% else %}
    <h3>Описание отсутствует</h3>
{% endif %}
<a href="{%url 'library:genre_list'%}">back</a>
</body>
</html>

book/templates/genre/genre_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Genre</title>
</head>
<body>
    <h1>Список жанров</h1>
    {% if  genre_list %}
        <ul>
            {% for genre in genre_list %}
                <li><a href="{% url 'library:genre' genre.id %}">{{ genre }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Нет информации</h2>
    {% endif %}
</body>
</html>

book/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Well come to our Libery</h1>
<h2>Where to go? Select one </h2>
<a href="{%url 'library:reward_list'%}">награды</a>
<a href="{%url 'library:genre_list'%}">жанры</a>
<a href="{%url 'library:book_list'%}">книги</a>
<a href="{%url 'library:author_list'%}">авторы</a>
</body>
</html>

book/templates/reward/reward.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{reward}}</h1>
{% if reward.description %}
    <h3>Описнаие награды: </h3>
    <h3>{{reward.description}}</h3>
    <h3>{{reward.data}}</h3>
{% else %}
    <h3>Описание отсутствует</h3>
{% endif %}
<a href="{%url 'library:genre_list'%}">back</a>

</body>
</html>

book/templates/reward/reward_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reward</title>
</head>
<body>
<h1>Список наград</h1>
    {% if  reward_list %}
        <ul>
            {% for reward in reward_list %}
                <li><a href="{% url 'library:reward' reward.id %}">{{ reward }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Нет информации</h2>
    {% endif %}
</body>
</html>